#!/usr/bin/env python3
"""Export the FlyWire network and world constants for the RTL.

Writes
  rtl/common/fly_cfg_pkg.sv        SystemVerilog package of constants
  rtl/common/network_weights.mem   N*N lines, hex byte W[dst][src] at dst*N+src

Both files are generated; edit model/fly_model/{constants,network}.py instead.
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "model"))
from fly_model import constants as C          # noqa: E402
from fly_model import network as net          # noqa: E402


def main():
    W = net.build_weights()
    out = ROOT / "rtl" / "common"
    out.mkdir(parents=True, exist_ok=True)

    with open(out / "network_weights.mem", "w", newline="\n") as f:
        for i in range(C.N_NEURONS):
            for j in range(C.N_NEURONS):
                f.write(f"{W[i][j] & 0xFF:02x}\n")

    consts = {
        "N_NEURONS": C.N_NEURONS,
        "THRESHOLD": net.THRESHOLD,
        "ARENA": C.ARENA,
        "FLY_X0": C.FLY_START[0], "FLY_Y0": C.FLY_START[1],
        "FLY_HEADING": C.FLY_HEADING,
        "FOOD_X0": C.FOOD_START[0], "FOOD_Y0": C.FOOD_START[1],
        "THREAT_X0": C.THREAT_START[0], "THREAT_Y0": C.THREAT_START[1],
        "TASTE_RADIUS": C.TASTE_RADIUS,
        "FOOD_DRIVE": C.FOOD_DRIVE,
        "LOOM_RADIUS": C.LOOM_RADIUS,
        "LOOM_BASE": C.LOOM_BASE,
        "LOOM_GAIN": C.LOOM_GAIN,
        "MOVE_WINDOW": C.MOVE_WINDOW,
        "ESCAPE_MIN": C.ESCAPE_MIN,
        "JUMP_DIST": C.JUMP_DIST,
        "FEED_MIN": C.FEED_MIN,
        "TURN_MARGIN": C.TURN_MARGIN,
        "BACK_MARGIN": C.BACK_MARGIN,
        "THREAT_PERIOD": C.THREAT_PERIOD,
        "FOOD_AHEAD": C.FOOD_AHEAD,
        "THREAT_SIDE": C.THREAT_SIDE,
    }
    # The RTL hard-codes the network's index ranges; fail loudly if they move.
    assert (net.FOOD_L, net.FOOD_R, net.THREAT_L, net.THREAT_R) == \
        (range(0, 8), range(8, 16), range(16, 24), range(24, 32))
    assert (net.GIANT_FIBER, net.MDN, net.DNP09, net.STEER_L, net.STEER_R, net.FEED) == \
        (range(232, 234), range(242, 246), range(246, 248), range(248, 250),
         range(250, 252), range(252, 256))
    lines = [
        "// fly_cfg_pkg.sv - GENERATED by model/export_rtl.py. Do not edit.",
        "// Source of truth: model/fly_model/constants.py and network.py (FlyWire FAFB v783 subcircuit)",
        "",
        "`timescale 1ns/1ps   // XSim requires every unit to have one when any unit does",
        "",
        "package fly_cfg_pkg;",
    ]
    for k, v in consts.items():
        lines.append(f"    localparam int {k:<14} = {v};")
    lines.append(f"    localparam logic [15:0] LFSR_SEED = 16'h{C.LFSR_SEED:04X};")
    lines.append("endpackage")
    (out / "fly_cfg_pkg.sv").write_text("\n".join(lines) + "\n", newline="\n") \
        if sys.version_info >= (3, 10) else (out / "fly_cfg_pkg.sv").write_text("\n".join(lines) + "\n")
    nz = sum(1 for row in W for w in row if w)
    print(f"exported {nz} nonzero synapses, threshold {net.THRESHOLD}, to {out}")


if __name__ == "__main__":
    main()
