// fly_cfg_pkg.sv - GENERATED by model/export_rtl.py. Do not edit.
// Source of truth: model/fly_model/constants.py and network.py (FlyWire FAFB v783 subcircuit)

`timescale 1ns/1ps   // XSim requires every unit to have one when any unit does

package fly_cfg_pkg;
    localparam int N_NEURONS      = 256;
    localparam int THRESHOLD      = 100;
    localparam int ARENA          = 64;
    localparam int FLY_X0         = 32;
    localparam int FLY_Y0         = 32;
    localparam int FLY_HEADING    = 0;
    localparam int FOOD_X0        = 8;
    localparam int FOOD_Y0        = 12;
    localparam int THREAT_X0      = 56;
    localparam int THREAT_Y0      = 52;
    localparam int TASTE_RADIUS   = 3;
    localparam int FOOD_DRIVE     = 60;
    localparam int LOOM_RADIUS    = 12;
    localparam int LOOM_BASE      = 40;
    localparam int LOOM_GAIN      = 5;
    localparam int MOVE_WINDOW    = 8;
    localparam int ESCAPE_MIN     = 1;
    localparam int JUMP_DIST      = 6;
    localparam int FEED_MIN       = 2;
    localparam int TURN_MARGIN    = 2;
    localparam int BACK_MARGIN    = 2;
    localparam int THREAT_PERIOD  = 3;
    localparam int FOOD_AHEAD     = 5;
    localparam int THREAT_SIDE    = 8;
    localparam logic [15:0] LFSR_SEED = 16'hACE1;
endpackage
